"""add applications and offer_letters tables

Revision ID: 5954ebdc55c3
Revises: 28dab035a172
Create Date: 2025-06-09 14:23:00.178274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5954ebdc55c3'
down_revision = '28dab035a172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_letters')
    op.drop_table('applications')
    # ### end Alembic commands ###
